<script>
  import { goto } from "$app/navigation";
</script>

<h1 class="text-white text-center">Dashboard</h1>
<div class="grid-container mt-8 text-white text-center mb-4">
  <div
    class="grid-item bg-kick-gold"
    on:click={() => {
      goto("/analyze");
    }}
  >
    <h3 class="bg-kick-gold mt-4">Analyze a new company</h3>
    <p class="bg-kick-gold mt-6">
      Run the company metrics through the algorithm
    </p>
  </div>
  <div
    class="grid-item bg-kick-gold"
    on:click={() => {
      goto("/edit");
    }}
  >
    <h3 class="bg-kick-gold mt-4">Edit previous company details</h3>
    <p class="bg-kick-gold mt-6">
      Edit the metrics of a previously analyzed company
    </p>
  </div>
  <div
    class="grid-item-full bg-kick-gold"
    on:click={() => {
      goto("/reports");
    }}
  >
    <h3 class="bg-kick-gold mt-4">View reports of analyzed companies</h3>
    <p class="bg-kick-gold mt-6">
      Undertand the parameters , decisions and the overall summary generated by
      the algorithm.
    </p>
  </div>
</div>

<style>
  .grid-container {
    display: grid;
    grid-template-rows: auto auto;
    grid-template-columns: auto auto;
    gap: 10px;
    border: 1px solid white;
    margin-left: 30px;
    margin-right: 30px;
  }

  .grid-item {
    border: 1px solid white;
    margin: 30px 80px;
    cursor: pointer;
    height: 120px;
  }

  .grid-item-full {
    grid-column: 1 / span 2;
    border: 1px solid white;
    margin: auto 80px 30px 80px;
    cursor: pointer;
    height: 120px;
  }
</style>
