<script>
  import { goto } from "$app/navigation";
  import { onMount } from "svelte";

  onMount(async () => {
    if (!localStorage.getItem("email")) {
      await goto("/");
    }
  });
</script>

<h1 class="text-white text-center text-2xl">Dashboard</h1>
<div class="grid-container mt-8 text-white text-center mb-4">
  <div
    class="grid-item bg-kick-gold"
    on:click={() => {
      goto("/analyze");
    }}
  >
    <h3 class="bg-kick-gold mt-4 text-xl font-semibold">
      Analyze a new company
    </h3>
    <p class="bg-kick-gold mt-6 text-black font-semibold">
      Run the company metrics through the algorithm
    </p>
  </div>
  <div
    class="grid-item bg-kick-gold"
    on:click={() => {
      goto("/edit");
    }}
  >
    <h3 class="bg-kick-gold mt-4 text-xl font-semibold">
      Edit previous company details
    </h3>
    <p class="bg-kick-gold mt-6 text-black font-semibold">
      Edit the metrics of a previously analyzed company
    </p>
  </div>
  <div
    class="grid-item-full bg-kick-gold"
    on:click={() => {
      goto("/reports");
    }}
  >
    <h3 class="bg-kick-gold mt-4 text-xl font-semibold">
      View reports of analyzed companies
    </h3>
    <p class="bg-kick-gold mt-6 text-black font-semibold">
      Understand the parameters , decisions and the overall summary generated by
      the algorithm.
    </p>
  </div>
</div>

<style>
  .grid-container {
    display: grid;
    grid-template-rows: auto auto;
    grid-template-columns: auto auto;
    border: 8px solid #cbb26a;
    border-radius: 8px;
    margin-left: 30px;
    margin-right: 30px;
  }

  .grid-item {
    /* border: 3px solid white; */
    transition: 400ms;
    border-radius: 8px;
    margin: 30px 80px;
    cursor: pointer;
    height: 120px;
  }

  .grid-item-full {
    grid-column: 1 / span 2;
    transition: 400ms;
    /* border: 3px solid white; */
    border-radius: 8px;
    margin: auto 80px 30px 80px;
    cursor: pointer;
    height: 120px;
  }

  .grid-item:hover,
  .grid-item-full:hover {
    box-shadow: 0 0 35px #cbb26a;
    transition: 400ms;
    border: 3px solid white;
  }
</style>
